### PR TITLE
Upgraded to jmeter version 3.3

### PR DESCRIPTION
**Pull request by nicholaspkbowden**
added failBuildOnError property so gradle build fails when jmeter tests
fail. Default property value is true

### CODE REVIEW

**Comment by nicholaspkbowden** [comment]
@foragerr 
@ojmendezz 
@emilong 
Please merge this pull request

**Comment by foragerr** [comment]
Thanks for contributing! @nicholaspkbowden

**Comment by nicholaspkbowden** [comment]
@foragerr thanks.

Can you build and publish this to a public repository, perhaps as a BETA release? I would like to pull in the plugin on a CI build and not have to rely on a local repository.

Thanks!

**Comment by foragerr** [comment]
For that I need to merge to master, and travis failed for that PR (#100), will try a build again.

**Pull request merged**
