### PR TITLE
Fixed typo in reference to jmGlobalProperties

### PR DESCRIPTION
**Pull request by ghost**
This should fix issue #104

### CODE REVIEW

**Comment by ghost** [comment]
It should fix the first issue at least.

**Comment by jjou1** [comment]
The fixes looked good to me.

**Comment by jjou1** [comment]
Can someone help out to code review and then merge the fix asap? This is blocking us for the test building and running. Thanks.

The reason I have to stick with this version (1.0.8-3.3) is that our tests have already using Jmeter V3_3 release version and some XML tags are not recognized by earlier version of Jmeter...

**Comment by foragerr** [comment]
Please use [v1.0.10-3.3](https://plugins.gradle.org/plugin/net.foragerr.jmeter/1.0.10-3.3)

**Pull request merged**
