### PR TITLE
JMeter 4.0

### PR DESCRIPTION
**Pull request by double16**

### CODE REVIEW

**Comment by foragerr** [comment]
Thank you for your contribution @double16, travis build failed though, would you mind taking a look at what's broken?

**Comment by djangofan** [comment]
I stopped using this plugin and now I use Taurus/bzt

**Comment by double16** [comment]
Looks like it was due to an older Gradle version.

**Comment by vgarmash-chwy** [comment]
@foragerr So... Since all checks passed, can you merge it, please?

**Pull request merged**
